//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetSportFinalHoussamEddineImhiouach
{
    public partial class MemberDashboard
    {
        protected global::System.Web.UI.WebControls.Label lblPaymentStatus;
        protected global::System.Web.UI.WebControls.Button btnProceedToPayment;
        protected global::System.Web.UI.WebControls.Literal ltTrainingSessions;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Button btnLogout;
    }
}
